import React from 'react'

const Contact = () => {
    return(
        <div class="address fl">
   <div class="im">
     г.Бишкек ул.Боконбаева 113
    <div class="call ">
     <div class="im">
     <a class="call_phone"> Тел: 0(000)123 456 </a>
                        <div class ='director'>
                        <br/>Директор: <br/> Баланчаев Тукунчо
                            <div class="call ">
                 <div class="im">
                 <a class="call_phone">Тел: 0(000)000 000 </a>
                                    <div class='referee'>
                                    <br/>Главный судья: <br/> Тукунчоев Баланча
                                        <div class="call ">
                             <div class="im">
                             <a class="call_phone">Тел: 0(000)000 000 </a>
                                                <div class='directors'>
                                                <br/>Директора: <br/>Теннисный корт                                  Тел:0(772)469 857 <br/>
                                                                     Спорт клуб К2                                  Тел:0(312)910 350<br/>
                                                                     T-CLUB                                       Тел:0(770)891 464<br/>
                                                                     KARVEN sport club                                 Тел:0(556)681 515<br/>
                                                                     Академия тенниса                                 Тел:0(555)543 850<br/>
                                                                     Мини Футбольное Поле "CHELSEA"                     Тел:0(551)915 014<br/>
                                                                     Футболистан                               Тел:0(550)960 960<br/>
                                                                    Бишкекский почтамт                                 Тел:0(312)662 154<br/>
                                                                    Центр оценки в образовании и методов обучения  Тел:0(312)664 838<br/>
                                                                    BeSmart.kg                                      Тел:0(770)547 810
                                                                    
                                                </div>
                                            </div>
                                        </div>  
                                    </div>
                                </div>   
                </div>
                        </div>
              </div>
                </div>
            </div>
        </div>
   

    )
}